#!/usr/bin/env bash
BRANCH=master
TARGET_REPO=kragniz/kragniz.github.io.git
PELICAN_OUTPUT_FOLDER=output

if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo -e "Starting to deploy to Github Pages\n"
    if [ "$TRAVIS" == "true" ]; then
        git config --global user.email "louis@kragniz.eu"
        git config --global user.name "Louis Taylor"
    fi

    git clone --quiet --branch=$BRANCH https://${GH_TOKEN}@github.com/$TARGET_REPO built_website > /dev/null
    cd built_website
    rsync -rv --exclude=.git  ../$PELICAN_OUTPUT_FOLDER/* .

    git add -f .
    git commit -m "Autocommit travis build #$TRAVIS_BUILD_NUMBER"
    git push -fq origin $BRANCH > /dev/null
    echo -e "Deploy completed\n"
fi
